const assert=require('node:assert/strict');
const {DecodedFrames,FramePresenter}=require('./replay_images.js');
const pending=[];
const createImage=()=>{const image={decode:()=>new Promise((resolve,reject)=>pending.push({image,resolve,reject}))};return image;};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
  const cache=new DecodedFrames({createImage,limit:4});
  const a=cache.get('a'),again=cache.get('a');
  assert.equal(a,again);assert.equal(pending.length,1);assert.equal(cache.peek('a'),null);
  pending.shift().resolve();const decoded=await a;assert.equal(cache.peek('a'),decoded);
  assert.equal(await cache.get('a'),decoded);assert.equal(pending.length,0);
  const commits=[],errors=[],busy=[];
  const presenter=new FramePresenter(cache,{busy:v=>busy.push(v),failure:e=>errors.push(e),delay:1000});
  assert.equal(await presenter.show('a',im=>commits.push(im.src)),true);
  assert.ok(!busy.includes(true),'Decoded playback must never show loading');
  const slow=presenter.show('slow',im=>commits.push(im.src));
  const latest=presenter.show('latest',im=>commits.push(im.src));
  assert.deepEqual(commits,['a'],'Keep existing frame/data while decoding');
  const first=pending.shift(),last=pending.shift();last.resolve();assert.equal(await latest,true);
  first.resolve();assert.equal(await slow,false);assert.deepEqual(commits,['a','latest']);
  const cancelled=presenter.show('cancelled',im=>commits.push(im.src));presenter.cancel();pending.shift().resolve();
  assert.equal(await cancelled,false);assert.deepEqual(commits,['a','latest']);
  const failed=presenter.show('missing',()=>assert.fail('Missing image must not commit data'));
  pending.shift().reject(new Error('missing'));assert.equal(await failed,false);assert.equal(errors.length,1);
  assert.equal(cache.cache.has('missing'),false,'Failed loads can be retried');
  const retry=cache.get('missing');pending.shift().resolve();await retry;
  const warming=cache.warm(['w1','w2','w3','w4','w5']);
  assert.equal(pending.length,3,'At most three speculative decodes');
  const abandoned=pending.splice(0);
  const replacement=cache.warm(['new']);const fresh=pending.shift();
  for(const p of abandoned)p.resolve();await tick();assert.equal(pending.length,0,'Old prefetch must not keep scheduling');
  fresh.resolve();await Promise.all([warming,replacement]);
  assert.ok(cache.cache.size<=4,'Decoded cache is bounded');
  presenter.cancel();
  console.log(JSON.stringify({status:'PASS',checks:['shared decode promise','retained decoded image','no loading on ready frame','atomic ready commit','latest seek wins','pause cancels pending frame','missing frame and retry','bounded cache','three-worker prefetch cancellation']}));
})().catch(error=>{console.error(error);process.exitCode=1;});
