'use strict';
const assert=require('node:assert/strict');
const {matches,outcome,reason,eventValue}=require('./app.js');
const f={truth:true,a:false,b:true,n:true,andCurrent:true,aHold:false,andHold:true,unknown:true};
assert.deepEqual(outcome(f),['rescue','新增正确报警']);
assert.match(reason(f),/B 与 N/);
assert.deepEqual(outcome({...f,truth:false}),['extra_fp','新增误报']);
assert.match(reason({...f,andCurrent:false}),/上一帧当前判断/);
assert.equal(eventValue({eventCount:0,delay:null},'delay'),'无事件');
assert.equal(eventValue({eventCount:1,delay:null},'delay'),'未检出');
assert.equal(eventValue({eventCount:1,delay:0},'delay'),'0.0 秒');
const c={id:'clip',layoutId:'g05',typeId:'head_horizontal',layer:'HEAD',stratum:'Core',relation:'INSIDE',tags:['rescue']};
const filters={group:'all',layer:'all',outcome:'all',search:''};
assert.equal(matches(c,{...filters,outcome:'rescue',search:'横向'}),true);
assert.equal(matches(c,{...filters,outcome:'miss'}),false);
assert.equal(matches(c,{...filters,group:'Boundary'}),false);
assert.equal(matches(c,{...filters,layer:'BODY'}),false);
assert.deepEqual(outcome({...f,unknown:false}),outcome(f));
console.log('PASS: 12 display semantics assertions');
